spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: none # create, create-drop, update, validate
    properties:
      hibernate:
        #show_sql: true
        default_batch_fetch_size: 1000
        format_sql: true
    open-in-view: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace


server:
  port: 8080
  error:
    include-binding-errors: always

